db:
  host: localhost
  port: 5432
  database: openpv
  table: buildings
  imports_table: imports
columns:
  id: id
  roof: roof
  wall: wall
  ground: ground
  filename: filename
  footprint: footprint
target_srs: 3857
